import { Injectable } from '@angular/core';
import { RefData, Applicant, Agency, AgencyServiceLevel } from '../models';

@Injectable({
  providedIn: 'root'
})
export class StaticDataService {

  formMap: any[] = [
      { field: 'reviewingAgencyId', text: 'Reviewing Agency ID' },
      { field: 'reason', text: 'Reason' },
      { field: 'requestingAgencyId', text: 'Rquesting Agency ID' },
      { field: 'appliedPosition', text: 'Position Applied For' },
      { field: 'payment', text: 'Payment' },
      { field: 'fingerPrintCardUser', text: 'Fingerprint Card User' },
      { field: 'lastName', text: 'Last Name' },
      { field: 'firstName', text: 'First Name' },
      { field: 'middleName', text: 'Middle Name' },
      { field: 'suffix', text: 'Suffix' },
      { field: 'socialSecurityNumber', text: 'Social Security #' },
      { field: 'dateOfBirth', text: 'Date of Birth' },
      { field: 'weight', text: 'Weight' },
      { field: 'gender', text: 'Sex' },
      { field: 'race', text: 'Race' },
      { field: 'eyeColor', text: 'Eye Color' },
      { field: 'hairColor', text: 'Hair Color' },
      { field: 'height', text: 'Height' },
      { field: 'placeOfBirth', text: 'Place of Birth' },
      { field: 'countryOfCitizenship', text: 'Country of Citizenship' },
      { field: 'stateDriversLicense', text: "State Driver's License" },
      { field: 'dirversLicenseNumber', text: "Driver's License #" },
      { field: 'phone', text: 'Phone' },
      { field: 'email', text: 'Email' },
      { field: 'address1', text: 'Address 1' },
      { field: 'address2', text: 'Address 2' },
      { field: 'city', text: 'City' },
      { field: 'apt', text: 'APT' },
      { field: 'state', text: 'State' },
      { field: 'zip', text: 'Zip' }
  ];

  citizenshipOptions: RefData[] = [
     { value: 'US', name: 'UNITED STATES' },
     { value: 'AF', name: 'AFGHANISTAN' },
     { value: 'AG', name: 'AGUASCALIENTES' },
     { value: 'AA', name: 'ALBANIA' },
     { value: 'AN', name: 'ALGERIA' },
     { value: 'YY', name: 'ALL OTHERS' },
     { value: 'AD', name: 'ANDORRA' },
     { value: 'AO', name: 'ANGOLA' },
     { value: 'AE', name: 'ANGUILLA' },
     { value: 'AI', name: 'ANTIGUA, BARBUDA' },
     { value: 'AT', name: 'ARGENTINA' },
     { value: 'AP', name: 'ARMENIA' },
     { value: 'AJ', name: 'ARUBA' },
     { value: 'AH', name: 'ASHMORE, CARTIER' },
     { value: 'AS', name: 'AUSTRALIA' },
     { value: 'AU', name: 'AUSTRIA' },
     { value: 'AV', name: 'AZERBAIJAN' },
     { value: 'AQ', name: 'AZORES ISLANDS' },
     { value: 'BD', name: 'BAHAMA ISLANDS' },
     { value: 'BE', name: 'BAHRAIN' },
     { value: 'BW', name: 'BALEARIC ISLANDS' },
     { value: 'BL', name: 'BANGLEDESH' },
     { value: 'BB', name: 'BARBADOS' },
     { value: 'BF', name: 'BASSAS DA INDIA' },
     { value: 'BG', name: 'BELGIUM' },
     { value: 'BH', name: 'BELIZE' },
     { value: 'DH', name: 'BENIN' },
     { value: 'BM', name: 'BERMUDA' },
     { value: 'BN', name: 'BHUTAN' },
     { value: 'BV', name: 'BOLIVIA' },
     { value: 'NX', name: 'BONAIRE/CURACAO' },
     { value: 'BP', name: 'BOSNIA HERCEGOVE' },
     { value: 'BT', name: 'BOTSWANA' },
     { value: 'BQ', name: 'BOUVET ISLAND' },
     { value: 'BO', name: 'BR. INDIAN OCEAN' },
     { value: 'BZ', name: 'BRAZIL' },
     { value: 'RB', name: 'BRAZZAVILLE' },
     { value: 'VB', name: 'BRITISH VIRGIN ISLANDS' },
     { value: 'BX', name: 'BRUNEI' },
     { value: 'BU', name: 'BULGARIA' },
     { value: 'UV', name: 'BURKINA FASO' },
     { value: 'BR', name: 'BURMA' },
     { value: 'BI', name: 'BURUNDI' },
     { value: 'BY', name: 'BYELARUS' },
     { value: 'CJ', name: 'CAMBODIA' },
     { value: 'CM', name: 'CAMEROON' },
     { value: 'CD', name: 'CANADA' },
     { value: 'ZI', name: 'CANARY ISLANDS' },
     { value: 'CV', name: 'CAPE VERDE ISLANDS' },
     { value: 'CP', name: 'CAYMAN ISLANDS' },
     { value: 'CW', name: 'CENTRAL AFRICAN REPUBLIC' },
     { value: 'CF', name: 'CHAD' },
     { value: 'CQ', name: 'CHILE' },
     { value: 'RC', name: 'CHINA' },
     { value: 'HR', name: 'CHRISTMAS ISLAND' },
     { value: 'DB', name: 'CLIPPERTON ISLAND' },
     { value: 'CB', name: 'COLUMBIA' },
     { value: 'DG', name: 'COMOROS ISLANDS' },
     { value: 'DI', name: 'COOK ISLANDS' },
     { value: 'DJ', name: 'CORAL SEA ISLAND' },
     { value: 'CR', name: 'COSTA RICA' },
     { value: 'KC', name: 'CROATIA' },
     { value: 'CC', name: 'CUBA' },
     { value: 'CS', name: 'CYPRUS' },
     { value: 'EZ', name: 'CZECH REPUBLIC' },
     { value: 'DK', name: 'DENMARK' },
     { value: 'DN', name: 'DJIBOUTI' },
     { value: 'DM', name: 'DOMINICA' },
     { value: 'DR', name: 'DOMINICAN REPUBLIC' },
     { value: 'EU', name: 'ECUADOR' },
     { value: 'EY', name: 'EGYPT' },
     { value: 'EL', name: 'EL SALVADOR' },
     { value: 'EN', name: 'ENGLAND, GREAT BRITAIN' },
     { value: 'EK', name: 'EQUATORIAL GUINEA' },
     { value: 'ES', name: 'ESTONIA' },
     { value: 'EO', name: 'ETHIOPIA' },
     { value: 'ER', name: 'EUROPA ISLAND' },
     { value: 'FA', name: 'FALKLAND ISLANDS' },
     { value: 'FO', name: 'FAROE ISLANDS' },
     { value: 'FJ', name: 'FIJI ISLANDS' },
     { value: 'FD', name: 'FINLAND' },
     { value: 'FN', name: 'FRANCE' },
     { value: 'FG', name: 'FRENCH GUIANA' },
     { value: 'FR', name: 'FRENCH OVERSEAS' },
     { value: 'FP', name: 'FRENCH POLYNESIA' },
     { value: 'GB', name: 'GABON' },
     { value: 'GK', name: 'GAMBIA' },
     { value: 'GZ', name: 'GAZA' },
     { value: 'GD', name: 'GEORGIA (RUSSIAN)' },
     { value: 'GS', name: 'GEORGIA/SANDWICH' },
     { value: 'GE', name: 'GERMANY' },
     { value: 'GG', name: 'GHANA' },
     { value: 'RG', name: 'GIBRALTAR' },
     { value: 'GO', name: 'GLORIOSO ISLANDS' },
     { value: 'GC', name: 'GREECE' },
     { value: 'GN', name: 'GREENLAND' },
     { value: 'GJ', name: 'GRENADA' },
     { value: 'GP', name: 'GUADELOUPE' },
     { value: 'GT', name: 'GUATEMALA' },
     { value: 'GF', name: 'GUERNSEY' },
     { value: 'GI', name: 'GUINEA' },
     { value: 'PG', name: 'GUINEA-BISSAU' },
     { value: 'GY', name: 'GUYANA' },
     { value: 'HT', name: 'HAITI' },
     { value: 'HE', name: 'HEARD/MCDONALD' },
     { value: 'NE', name: 'HOLLAND, NETHERLANDS' },
     { value: 'HD', name: 'HONDURAS' },
     { value: 'HK', name: 'HONG KONG' },
     { value: 'HU', name: 'HUNGARY' },
     { value: 'IC', name: 'ICELAND' },
     { value: 'II', name: 'INDIA' },
     { value: 'IO', name: 'INDONESIA' },
     { value: 'IR', name: 'IRAN' },
     { value: 'IQ', name: 'IRAQ' },
     { value: 'IE', name: 'IRELAND' },
     { value: 'IB', name: 'ISLE OF MAN' },
     { value: 'IS', name: 'ISRAEL' },
     { value: 'IT', name: 'ITALY (INCLUDES SICILY)' },
     { value: 'IY', name: 'IVORY COAST' },
     { value: 'JM', name: 'JAMAICA' },
     { value: 'JN', name: 'JAN MAYEN' },
     { value: 'JA', name: 'JAPAN' },
     { value: 'JE', name: 'JERSEY' },
     { value: 'JO', name: 'JORDAN' },
     { value: 'JU', name: 'JUAN DE NOVA ISLAND' },
     { value: 'KT', name: 'KAZAKHSTAN' },
     { value: 'DD', name: 'KEELING ISLANDS' },
     { value: 'KE', name: 'KENYA' },
     { value: 'KB', name: 'KIRIBATI' },
     { value: 'KU', name: 'KUWAIT' },
     { value: 'KZ', name: 'KYRGYZSTAN' },
     { value: 'LS', name: 'LAOS' },
     { value: 'LN', name: 'LEBANON' },
     { value: 'LE', name: 'LESOTHO' },
     { value: 'LB', name: 'LIBERIA' },
     { value: 'LY', name: 'LIBYA' },
     { value: 'LI', name: 'LIECHTENSTEIN' },
     { value: 'LX', name: 'LUXEMBOURG' },
     { value: 'OC', name: 'MACAU' },
     { value: 'IM', name: 'MADEIRA ISLANDS' },
     { value: 'MP', name: 'MALAGASY REPUBLIC (INCLUDES MADAGASCAR)' },
     { value: 'MF', name: 'MALAWI' },
     { value: 'MZ', name: 'MALAYSIA' },
     { value: 'MV', name: 'MALDIVES' },
     { value: 'ML', name: 'MALI' },
     { value: 'MY', name: 'MALTA' },
     { value: 'KH', name: 'MANAHIKI ISLAND' },
     { value: 'ZB', name: 'MARTINIQUE' },
     { value: 'MU', name: 'MAURITANIA' },
     { value: 'UM', name: 'MAURITIUS' },
     { value: 'YO', name: 'MAYOTTE' },
     { value: 'MM', name: 'MEXICO' },
     { value: 'FS', name: 'MICRONESIA' },
     { value: 'LD', name: 'MOLDOVA' },
     { value: 'MJ', name: 'MONACO' },
     { value: 'MG', name: 'MONGOLIA' },
     { value: 'RR', name: 'MONTSERRAT' },
     { value: 'MQ', name: 'MOROCCO' },
     { value: 'ZO', name: 'MOZAMBIQUE' },
     { value: 'SJ', name: 'NAMIBIA, SOUTH WEST AFRICA' },
     { value: 'NR', name: 'NAURU' },
     { value: 'NP', name: 'NEPAL' },
     { value: 'NQ', name: 'NEW CALEDONIA' },
     { value: 'NO', name: 'NEW GUINEA PAPUA' },
     { value: 'NZ', name: 'NEW ZEALAND' },
     { value: 'NU', name: 'NICARAGUA' },
     { value: 'NN', name: 'NIGER' },
     { value: 'NG', name: 'NIGERIA' },
     { value: 'IU', name: 'NIUE' },
     { value: 'OF', name: 'NORFOLK ISLAND' },
     { value: 'KN', name: 'NORTH KOREA' },
     { value: 'NI', name: 'NORTHERN IRELAND' },
     { value: 'NW', name: 'NORWAY' },
     { value: 'OI', name: 'OKINAWA' },
     { value: 'OM', name: 'OMAN' },
     { value: 'TD', name: 'PACIFIC ISLANDS' },
     { value: 'PK', name: 'PAKISTAN' },
     { value: 'PD', name: 'PALAU' },
     { value: 'PM', name: 'PANAMA' },
     { value: 'PF', name: 'PARACEL ISLANDS' },
     { value: 'PV', name: 'PARAGUAY' },
     { value: 'PU', name: 'PERU' },
     { value: 'PI', name: 'PHILIPPINES' },
     { value: 'PC', name: 'PITCAIRN ISLANDS' },
     { value: 'PO', name: 'POLAND' },
     { value: 'PT', name: 'PORTUGAL' },
     { value: 'PB', name: 'PUEBLA' },
     { value: 'QA', name: 'QATAR' },
     { value: 'QU', name: 'QUERETARO' },
     { value: 'RE', name: 'REUNION' },
     { value: 'RH', name: 'RHODESIA, ZIMBABWE' },
     { value: 'RU', name: 'ROMANIA' },
     { value: 'RA', name: 'RUSSIA, SOVIET UNION, USSR' },
     { value: 'RF', name: 'RUSSIAN FED.' },
     { value: 'RW', name: 'RWANDA' },
     { value: 'HS', name: 'SAINT HELENA' },
     { value: 'LU', name: 'SAINT LUCIA' },
     { value: 'SH', name: 'SAN MARINO' },
     { value: 'TP', name: 'SAOTOME/PRINCIPE' },
     { value: 'SB', name: 'SAUDIA ARABIA' },
     { value: 'SS', name: 'SCOTLAND' },
     { value: 'SG', name: 'SENEGAL' },
     { value: 'SE', name: 'SEYCHELLES' },
     { value: 'KP', name: 'SHAKOPEE' },
     { value: 'SA', name: 'SIERRA LEONE' },
     { value: 'SR', name: 'SINGAPORE' },
     { value: 'LF', name: 'SLOVAKIA' },
     { value: 'LO', name: 'SLOVENIA' },
     { value: 'BS', name: 'SOLOMON ISLANDS' },
     { value: 'SM', name: 'SOMALIA' },
     { value: 'SF', name: 'SOUTH AFRICA' },
     { value: 'KO', name: 'SOUTH KOREA' },
     { value: 'SP', name: 'SPAIN' },
     { value: 'TE', name: 'SPRATLY ISLANDS' },
     { value: 'CY', name: 'SRI LANKA, CEYLON' },
     { value: 'TS', name: 'ST. KITTS/NEVIS' },
     { value: 'PS', name: 'ST. PIERRE/MIQUEL' },
     { value: 'VV', name: 'ST. VINCENT/GRENADIN' },
     { value: 'SU', name: 'SUDAN' },
     { value: 'ZC', name: 'SURINAM' },
     { value: 'SV', name: 'SVALBARD' },
     { value: 'SW', name: 'SWAZILAND' },
     { value: 'SQ', name: 'SWEDEN' },
     { value: 'SZ', name: 'SWITZERLAND' },
     { value: 'SY', name: 'SYRIA' },
     { value: 'TW', name: 'TAIWAN' },
     { value: 'TJ', name: 'TAJIKISTAN' },
     { value: 'TZ', name: 'TANZANIA' },
     { value: 'TH', name: 'THAILAND' },
     { value: 'TO', name: 'TOGO' },
     { value: 'TK', name: 'TOKELAU' },
     { value: 'TG', name: 'TONGA' },
     { value: 'TQ', name: 'TONGAREVA' },
     { value: 'TT', name: 'TRINIDAD &amp; TOBAGO' },
     { value: 'TM', name: 'TROMELIN ISLAND' },
     { value: 'TF', name: 'TUAMOTU ARCHIPEL' },
     { value: 'TU', name: 'TUNISIA' },
     { value: 'TY', name: 'TURKEY' },
     { value: 'UR', name: 'TURKMENISTAN' },
     { value: 'TR', name: 'TURKS/CALCOS ISLANDS' },
     { value: 'TV', name: 'TUVALU' },
     { value: 'UG', name: 'UGANDA' },
     { value: 'UK', name: 'UKRAINE' },
     { value: 'TC', name: 'UNITED ARAB EMIR' },
     { value: 'XX', name: 'UNKNOWN' },
     { value: 'UY', name: 'URUGUAY' },
     { value: 'UZ', name: 'UZBEKISTAN' },
     { value: 'HN', name: 'VANUATA' },
     { value: 'VY', name: 'VATICAN CITY' },
     { value: 'VZ', name: 'VENEZUELA' },
     { value: 'RV', name: 'VIETNAM' },
     { value: 'WL', name: 'WALES' },
     { value: 'WF', name: 'WALLIS/FUTUNA' },
     { value: 'WB', name: 'WEST BANK' },
     { value: 'WG', name: 'WEST GERMANY' },
     { value: 'RS', name: 'WESTERN SAHARA' },
     { value: 'WS', name: 'WESTERN SAMOA' },
     { value: 'RY', name: 'YEMEN' },
     { value: 'ZR', name: 'ZAIRE' },
     { value: 'ZM', name: 'ZAMBIA' }
   ];

  eyeColorOptions: RefData[] =  [
    { value: 'BLK', name: 'Black' },
    { value: 'BLU', name: 'Blue' },
    { value: 'BRO', name: 'Brown' },
    { value: 'GRN', name: 'Green' },
    { value: 'GRY', name: 'Gray' },
    { value: 'HAZ', name: 'Hazel' },
    { value: 'MAR', name: 'Maroon' },
    { value: 'MUL', name: 'Multicolored' },
    { value: 'PNK', name: 'Pink' },
    { value: 'XXX', name: 'Unknown' }
  ];

  hairColorOptions: RefData[] =  [
    { value: 'BLK', name: 'Black' },
    { value: 'BLN', name: 'Blonde' },
    { value: 'BLU', name: 'Blue' },
    { value: 'BRO', name: 'Brown' },
    { value: 'GRY', name: 'Gray' },
    { value: 'ONG', name: 'Orange' },
    { value: 'PLE', name: 'Purple' },
    { value: 'PNK', name: 'Pink' },
    { value: 'RED', name: 'Red' },
    { value: 'SDY', name: 'Sandy' },
    { value: 'WHI', name: 'White' },
    { value: 'XXX', name: 'Ukn/Bald' }
  ];


  heightOptions: RefData[] =  [
    { value: '000', name: "UNKNOWN" },
    { value: '400', name: "4'00" },
    { value: '401', name: "4'01" },
    { value: '402', name: "4'02" },
    { value: '403', name: "4'03" },
    { value: '404', name: "4'04" },
    { value: '405', name: "4'05" },
    { value: '406', name: "4'06" },
    { value: '407', name: "4'07" },
    { value: '408', name: "4'08" },
    { value: '409', name: "4'09" },
    { value: '410', name: "4'10" },
    { value: '411', name: "4'11" },
    { value: '500', name: "5'00" },
    { value: '501', name: "5'01" },
    { value: '502', name: "5'02" },
    { value: '503', name: "5'03" },
    { value: '504', name: "5'04" },
    { value: '505', name: "5'05" },
    { value: '506', name: "5'06" },
    { value: '507', name: "5'07" },
    { value: '508', name: "5'08" },
    { value: '509', name: "5'09" },
    { value: '510', name: "5'10" },
    { value: '511', name: "5'11" },
    { value: '600', name: "6'00" },
    { value: '601', name: "6'01" },
    { value: '602', name: "6'02" },
    { value: '603', name: "6'03" },
    { value: '604', name: "6'04" },
    { value: '605', name: "6'05" },
    { value: '606', name: "6'06" },
    { value: '607', name: "6'07" },
    { value: '608', name: "6'08" },
    { value: '609', name: "6'09" },
    { value: '610', name: "6'10" },
    { value: '611', name: "6'11" },
    { value: '700', name: "7'00" },
    { value: '701', name: "7'01" },
    { value: '702', name: "7'02" },
    { value: '703', name: "7'03" },
    { value: '704', name: "7'04" },
    { value: '705', name: "7'05" },
    { value: '706', name: "7'06" },
    { value: '707', name: "7'07" },
    { value: '708', name: "7'08" },
    { value: '709', name: "7'09" },
    { value: '710', name: "7'10" },
    { value: '711', name: "7'11" }
  ];

  placeOfBirthOptions: RefData[] = [
    { value: 'AK', name: 'ALASKA' },
    { value: 'AL', name: 'ALABAMA' },
    { value: 'AR', name: 'ARKANSAS' },
    { value: 'AZ', name: 'ARIZONA' },
    { value: 'CA', name: 'CALIFORNIA' },
    { value: 'CO', name: 'COLORADO' },
    { value: 'CT', name: 'CONNECTICUT' },
    { value: 'DC', name: 'DISTRICT OF COLUMBIA' },
    { value: 'DE', name: 'DELAWARE' },
    { value: 'FL', name: 'FLORIDA' },
    { value: 'GA', name: 'GEORGIA' },
    { value: 'HI', name: 'HAWAII' },
    { value: 'IA', name: 'IOWA' },
    { value: 'ID', name: 'IDAHO' },
    { value: 'IL', name: 'ILLINOIS' },
    { value: 'IN', name: 'INDIANA' },
    { value: 'KS', name: 'KANSAS' },
    { value: 'KY', name: 'KENTUCKY' },
    { value: 'LA', name: 'LOUISIANA' },
    { value: 'MA', name: 'MASSACHUSETTS' },
    { value: 'MD', name: 'MARYLAND' },
    { value: 'ME', name: 'MAINE' },
    { value: 'MI', name: 'MICHIGAN' },
    { value: 'MN', name: 'MINNESOTA' },
    { value: 'MO', name: 'MISSOURI' },
    { value: 'MS', name: 'MISSISSIPPI' },
    { value: 'MT', name: 'MONTANA' },
    { value: 'NB', name: 'NEBRASKA' },
    { value: 'NC', name: 'NORTH CAROLINA' },
    { value: 'ND', name: 'NORTH DAKOTA' },
    { value: 'NH', name: 'NEW HAMPSHIRE' },
    { value: 'NJ', name: 'NEW JERSEY' },
    { value: 'NM', name: 'NEW MEXICO' },
    { value: 'NV', name: 'NEVADA' },
    { value: 'NY', name: 'NEW YORK' },
    { value: 'OH', name: 'OHIO' },
    { value: 'OK', name: 'OKLAHOMA' },
    { value: 'OR', name: 'OREGON' },
    { value: 'PA', name: 'PENNSYLVANIA' },
    { value: 'RI', name: 'RHODE ISLAND' },
    { value: 'SC', name: 'SOUTH CAROLINA' },
    { value: 'SD', name: 'SOUTH DAKOTA' },
    { value: 'TN', name: 'TENNESSEE' },
    { value: 'TX', name: 'TEXAS' },
    { value: 'UT', name: 'UTAH' },
    { value: 'VA', name: 'VIRGINIA' },
    { value: 'VT', name: 'VERMONT' },
    { value: 'WA', name: 'WASHINGTON' },
    { value: 'WI', name: 'WISCONSIN' },
    { value: 'WV', name: 'WEST VIRGINIA' },
    { value: 'WY', name: 'WYOMING' },
    { value: 'AA', name: 'ALBANIA' },
    { value: 'AB', name: 'ALBERTA' },
    { value: 'AD', name: 'ANDORRA' },
    { value: 'AE', name: 'ANGUILLA' },
    { value: 'AF', name: 'AFGHANISTAN' },
    { value: 'AG', name: 'AGUASCALIENTES' },
    { value: 'AH', name: 'ASHMORE, CARTIER' },
    { value: 'AI', name: 'ANTIGUA, BARBUDA' },
    { value: 'AJ', name: 'ARUBA' },
    { value: 'AM', name: 'AMERICAN SAMOA' },
    { value: 'AN', name: 'ALGERIA' },
    { value: 'AO', name: 'ANGOLA' },
    { value: 'AP', name: 'ARMENIA' },
    { value: 'AQ', name: 'AZORES ISLANDS' },
    { value: 'AS', name: 'AUSTRALIA' },
    { value: 'AT', name: 'ARGENTINA' },
    { value: 'AU', name: 'AUSTRIA' },
    { value: 'AV', name: 'AZERBAIJAN' },
    { value: 'BA', name: 'BAJA CALIFORNIA' },
    { value: 'BB', name: 'BARBADOS' },
    { value: 'BC', name: 'BRITISH COLUMBIA' },
    { value: 'BD', name: 'BAHAMA ISLANDS' },
    { value: 'BE', name: 'BAHRAIN' },
    { value: 'BF', name: 'BASSAS DA INDIA' },
    { value: 'BG', name: 'BELGIUM' },
    { value: 'BH', name: 'BELIZE' },
    { value: 'BI', name: 'BURUNDI' },
    { value: 'BJ', name: 'BAJA CALIFORNIA SUR' },
    { value: 'BK', name: 'BAKER ISLAND' },
    { value: 'BL', name: 'BANGLEDESH' },
    { value: 'BM', name: 'BERMUDA' },
    { value: 'BN', name: 'BHUTAN' },
    { value: 'BO', name: 'BR. INDIAN OCEAN' },
    { value: 'BP', name: 'BOSNIA HERCEGOVE' },
    { value: 'BQ', name: 'BOUVET ISLAND' },
    { value: 'BR', name: 'BURMA' },
    { value: 'BS', name: 'SOLOMON ISLANDS' },
    { value: 'BT', name: 'BOTSWANA' },
    { value: 'BU', name: 'BULGARIA' },
    { value: 'BV', name: 'BOLIVIA' },
    { value: 'BW', name: 'BALEARIC ISLANDS' },
    { value: 'BX', name: 'BRUNEI' },
    { value: 'BY', name: 'BYELARUS' },
    { value: 'BZ', name: 'BRAZIL' },
    { value: 'CB', name: 'COLOMBIA' },
    { value: 'CC', name: 'CUBA' },
    { value: 'CD', name: 'CANADA' },
    { value: 'CE', name: 'CAMPECHE' },
    { value: 'CF', name: 'CHAD' },
    { value: 'CG', name: 'CAROLINE ISLANDS' },
    { value: 'CH', name: 'CHIHUAHUA' },
    { value: 'CI', name: 'CHIAPAS' },
    { value: 'CJ', name: 'CAMBODIA' },
    { value: 'CL', name: 'COLIMA' },
    { value: 'CM', name: 'CAMEROON' },
    { value: 'CP', name: 'CAYMAN ISLANDS' },
    { value: 'CQ', name: 'CHILE' },
    { value: 'CR', name: 'COSTA RICA' },
    { value: 'CS', name: 'CYPRUS' },
    { value: 'CU', name: 'COAHUILA' },
    { value: 'CV', name: 'CAPE VERDE ISLANDS' },
    { value: 'CW', name: 'CENTRAL AFRICAN REPUBLIC' },
    { value: 'CY', name: 'SRI LANKA, CEYLON' },
    { value: 'CZ', name: 'CANAL ZONE' },
    { value: 'DB', name: 'CLIPPERTON ISLAND' },
    { value: 'DD', name: 'KEELING ISLANDS' },
    { value: 'DF', name: 'DISTRITO FEDERAL' },
    { value: 'DG', name: 'COMOROS ISLANDS' },
    { value: 'DH', name: 'BENIN' },
    { value: 'DI', name: 'COOK ISLANDS' },
    { value: 'DJ', name: 'CORAL SEA ISLAND' },
    { value: 'DK', name: 'DENMARK' },
    { value: 'DL', name: 'DEVIL LAKE SIOUX' },
    { value: 'DM', name: 'DOMINICA' },
    { value: 'DN', name: 'DJIBOUTI' },
    { value: 'DO', name: 'DURANGO' },
    { value: 'DR', name: 'DOMINICAN REPUBLIC' },
    { value: 'EE', name: 'ABSENTEE SHAWNEE' },
    { value: 'EK', name: 'EQUATORIAL GUINEA' },
    { value: 'EL', name: 'EL SALVADOR' },
    { value: 'EN', name: 'ENGLAND, GREAT BRITAIN' },
    { value: 'EO', name: 'ETHIOPIA' },
    { value: 'ER', name: 'EUROPA ISLAND' },
    { value: 'ES', name: 'ESTONIA' },
    { value: 'ET', name: 'ERETRIA' },
    { value: 'EU', name: 'ECUADOR' },
    { value: 'EY', name: 'EGYPT' },
    { value: 'EZ', name: 'CZECH REPUBLIC' },
    { value: 'FA', name: 'FALKLAND ISLANDS' },
    { value: 'FC', name: 'FOND DU LAC' },
    { value: 'FD', name: 'FINLAND' },
    { value: 'FG', name: 'FRENCH GUIANA' },
    { value: 'FJ', name: 'FIJI ISLANDS' },
    { value: 'FN', name: 'FRANCE' },
    { value: 'FO', name: 'FAROE ISLANDS' },
    { value: 'FP', name: 'FRENCH POLYNESIA' },
    { value: 'FR', name: 'FRENCH OVERSEAS' },
    { value: 'FS', name: 'MICRONESIA' },
    { value: 'FX', name: 'SAC &amp; FOX' },
    { value: 'GB', name: 'GABON' },
    { value: 'GC', name: 'GREECE' },
    { value: 'GD', name: 'GEORGIA (RUSSIAN)' },
    { value: 'GE', name: 'GERMANY' },
    { value: 'GF', name: 'GUERNSEY' },
    { value: 'GG', name: 'GHANA' },
    { value: 'GI', name: 'GUINEA' },
    { value: 'GJ', name: 'GRENADA' },
    { value: 'GK', name: 'GAMBIA' },
    { value: 'GM', name: 'GUAM' },
    { value: 'GN', name: 'GREENLAND' },
    { value: 'GO', name: 'GLORIOSO ISLANDS' },
    { value: 'GP', name: 'GUADELOUPE' },
    { value: 'GR', name: 'GUERRERO' },
    { value: 'GS', name: 'GEORGIA/SANDWICH' },
    { value: 'GT', name: 'GUATEMALA' },
    { value: 'GU', name: 'GUANAJUATO' },
    { value: 'GY', name: 'GUYANA' },
    { value: 'GZ', name: 'GAZA' },
    { value: 'HD', name: 'HONDURAS' },
    { value: 'HE', name: 'HEARD/MCDONALD' },
    { value: 'HK', name: 'HONG KONG' },
    { value: 'HL', name: 'HIDALGO' },
    { value: 'HN', name: 'VANUATA' },
    { value: 'HO', name: 'HOWLAND ISLAND' },
    { value: 'HR', name: 'CHRISTMAS ISLAND' },
    { value: 'HS', name: 'SAINT HELENA' },
    { value: 'HT', name: 'HAITI' },
    { value: 'HU', name: 'HUNGARY' },
    { value: 'IB', name: 'ISLE OF MAN' },
    { value: 'IC', name: 'ICELAND' },
    { value: 'IE', name: 'IRELAND' },
    { value: 'II', name: 'INDIA' },
    { value: 'IM', name: 'MADEIRA ISLANDS' },
    { value: 'IO', name: 'INDONESIA' },
    { value: 'IQ', name: 'IRAQ' },
    { value: 'IR', name: 'IRAN' },
    { value: 'IS', name: 'ISRAEL' },
    { value: 'IT', name: 'ITALY (INCLUDES SICILY)' },
    { value: 'IU', name: 'NIUE' },
    { value: 'IX', name: 'MENOMINEE' },
    { value: 'IY', name: 'IVORY COAST' },
    { value: 'JA', name: 'JAPAN' },
    { value: 'JE', name: 'JERSEY' },
    { value: 'JI', name: 'JOHNSTON ATOLL' },
    { value: 'JL', name: 'JALISCO' },
    { value: 'JM', name: 'JAMAICA' },
    { value: 'JN', name: 'JAN MAYEN' },
    { value: 'JO', name: 'JORDAN' },
    { value: 'JR', name: 'JARVIS ISLAND' },
    { value: 'JU', name: 'JUAN DE NOVA ISLAND' },
    { value: 'KB', name: 'KIRIBATI' },
    { value: 'KC', name: 'CROATIA' },
    { value: 'KE', name: 'KENYA' },
    { value: 'KH', name: 'MANAHIKI ISLAND' },
    { value: 'KI', name: 'KINGMAN REEF' },
    { value: 'KN', name: 'NORTH KOREA' },
    { value: 'KO', name: 'SOUTH KOREA' },
    { value: 'KP', name: 'SHAKOPEE' },
    { value: 'KT', name: 'KAZAKHSTAN' },
    { value: 'KU', name: 'KUWAIT' },
    { value: 'KW', name: 'KIOWA' },
    { value: 'KZ', name: 'KYRGYZSTAN' },
    { value: 'LB', name: 'LIBERIA' },
    { value: 'LC', name: 'MILLE LACS' },
    { value: 'LD', name: 'MOLDOVA' },
    { value: 'LE', name: 'LESOTHO' },
    { value: 'LF', name: 'SLOVAKIA' },
    { value: 'LH', name: 'LITHUANIA' },
    { value: 'LI', name: 'LIECHTENSTEIN' },
    { value: 'LL', name: 'LEECHLK CHIPPEWA' },
    { value: 'LN', name: 'LEBANON' },
    { value: 'LO', name: 'SLOVENIA' },
    { value: 'LP', name: 'LAC DU FLAMBEAU' },
    { value: 'LS', name: 'LAOS' },
    { value: 'LT', name: 'LATVIA' },
    { value: 'LU', name: 'SAINT LUCIA' },
    { value: 'LX', name: 'LUXEMBOURG' },
    { value: 'LY', name: 'LIBYA' },
    { value: 'MB', name: 'MANITOBA' },
    { value: 'MC', name: 'MICHOACAN' },
    { value: 'MF', name: 'MALAWI' },
    { value: 'MG', name: 'MONGOLIA' },
    { value: 'MH', name: 'MARSHALL ISLANDS' },
    { value: 'MJ', name: 'MONACO' },
    { value: 'MK', name: 'MARIANAS ISLANDS' },
    { value: 'ML', name: 'MALI' },
    { value: 'MM', name: 'MEXICO' },
    { value: 'MP', name: 'MALAGASY REPUBLIC (INCLUDES MADA' },
    { value: 'MQ', name: 'MOROCCO' },
    { value: 'MR', name: 'MORELOS' },
    { value: 'MU', name: 'MAURITANIA' },
    { value: 'MV', name: 'MALDIVES' },
    { value: 'MW', name: 'MIDWAY ISLAND' },
    { value: 'MY', name: 'MALTA' },
    { value: 'MZ', name: 'MALAYSIA' },
    { value: 'NA', name: 'NAYARIT' },
    { value: 'NE', name: 'NETHERLANDS' },
    { value: 'NF', name: 'NEWFOUNDLAND' },
    { value: 'NG', name: 'NIGERIA' },
    { value: 'NI', name: 'NORTHERN IRELAND' },
    { value: 'NK', name: 'NEW BRUNSWICK' },
    { value: 'NL', name: 'NUEVO LEON' },
    { value: 'NN', name: 'NIGER' },
    { value: 'NO', name: 'NEW GUINEA PAPUA' },
    { value: 'NP', name: 'NEPAL' },
    { value: 'NQ', name: 'NEW CALEDONIA' },
    { value: 'NR', name: 'NAURU' },
    { value: 'NS', name: 'NOVA SCOTIA' },
    { value: 'NT', name: 'NORTHWEST TERRITORY' },
    { value: 'NU', name: 'NICARAGUA' },
    { value: 'NW', name: 'NORWAY' },
    { value: 'NX', name: 'BONAIRE/CURACAO' },
    { value: 'NZ', name: 'NEW ZEALAND' },
    { value: 'OA', name: 'OAXACA' },
    { value: 'OC', name: 'MACAU' },
    { value: 'OF', name: 'NORFOLK ISLAND' },
    { value: 'OI', name: 'OKINAWA' },
    { value: 'OM', name: 'OMAN' },
    { value: 'ON', name: 'ONTARIO' },
    { value: 'OS', name: 'OGLALA SIOUX' },
    { value: 'PB', name: 'PUEBLA' },
    { value: 'PC', name: 'PITCAIRN ISLANDS' },
    { value: 'PD', name: 'PALAU' },
    { value: 'PE', name: 'PRINCE EDWARD ISLAND' },
    { value: 'PF', name: 'PARACEL ISLANDS' },
    { value: 'PG', name: 'GUINEA-BISSAU' },
    { value: 'PI', name: 'PHILIPPINES' },
    { value: 'PK', name: 'PAKISTAN' },
    { value: 'PL', name: 'PALMYRA ATOLL' },
    { value: 'PM', name: 'PANAMA' },
    { value: 'PO', name: 'POLAND' },
    { value: 'PQ', name: 'QUEBEC' },
    { value: 'PR', name: 'PUERTO RICO' },
    { value: 'PS', name: 'ST. PIERRE/MIQUEL' },
    { value: 'PT', name: 'PORTUGAL' },
    { value: 'PU', name: 'PERU' },
    { value: 'PV', name: 'PARAGUAY' },
    { value: 'QA', name: 'QATAR' },
    { value: 'QR', name: 'QUINTANA ROO' },
    { value: 'QU', name: 'QUERETARO' },
    { value: 'RA', name: 'RUSSIA, SOVIET UNION, USSR' },
    { value: 'RB', name: 'BRAZZAVILLE' },
    { value: 'RC', name: 'CHINA' },
    { value: 'RE', name: 'REUNION' },
    { value: 'RF', name: 'RUSSIAN FED.' },
    { value: 'RG', name: 'GIBRALTAR' },
    { value: 'RH', name: 'RHODESIA, ZIMBABWE' },
    { value: 'RL', name: 'RED LAKE' },
    { value: 'RR', name: 'MONTSERRAT' },
    { value: 'RS', name: 'WESTERN SAHARA' },
    { value: 'RU', name: 'ROMANIA' },
    { value: 'RV', name: 'VIETNAM' },
    { value: 'RW', name: 'RWANDA' },
    { value: 'RY', name: 'YEMEN' },
    { value: 'SA', name: 'SIERRA LEONE' },
    { value: 'SB', name: 'SAUDIA ARABIA' },
    { value: 'SE', name: 'SEYCHELLES' },
    { value: 'SF', name: 'SOUTH AFRICA' },
    { value: 'SG', name: 'SENEGAL' },
    { value: 'SH', name: 'SAN MARINO' },
    { value: 'SI', name: 'SINALOA' },
    { value: 'SJ', name: 'NAMIBIA, SOUTH WEST AFRICA' },
    { value: 'SL', name: 'SAN LUIS POTOSI' },
    { value: 'SM', name: 'SOMALIA' },
    { value: 'SN', name: 'SASKATCHEWAN' },
    { value: 'SO', name: 'SONORA' },
    { value: 'SP', name: 'SPAIN' },
    { value: 'SQ', name: 'SWEDEN' },
    { value: 'SR', name: 'SINGAPORE' },
    { value: 'SS', name: 'SCOTLAND' },
    { value: 'ST', name: 'PEOPLES DEMOCRATIC REPUBLIC OF Y' },
    { value: 'SU', name: 'SUDAN' },
    { value: 'SV', name: 'SVALBARD' },
    { value: 'SW', name: 'SWAZILAND' },
    { value: 'SY', name: 'SYRIA' },
    { value: 'SZ', name: 'SWITZERLAND' },
    { value: 'TA', name: 'TAMAULIPAS' },
    { value: 'TB', name: 'TABASCO' },
    { value: 'TC', name: 'UNITED ARAB EMIR' },
    { value: 'TD', name: 'PACIFIC ISLANDS' },
    { value: 'TE', name: 'SPRATLY ISLANDS' },
    { value: 'TF', name: 'TUAMOTU ARCHIPEL' },
    { value: 'TG', name: 'TONGA' },
    { value: 'TH', name: 'THAILAND' },
    { value: 'TJ', name: 'TAJIKISTAN' },
    { value: 'TK', name: 'TOKELAU' },
    { value: 'TL', name: 'TLAXCALA' },
    { value: 'TM', name: 'TROMELIN ISLAND' },
    { value: 'TO', name: 'TOGO' },
    { value: 'TP', name: 'SAOTOME/PRINCIPE' },
    { value: 'TQ', name: 'TONGAREVA' },
    { value: 'TR', name: 'TURKS/CALCOS ISLANDS' },
    { value: 'TS', name: 'ST. KITTS/NEVIS' },
    { value: 'TT', name: 'TRINIDAD &amp; TOBAGO' },
    { value: 'TU', name: 'TUNISIA' },
    { value: 'TV', name: 'TUVALU' },
    { value: 'TW', name: 'TAIWAN' },
    { value: 'TY', name: 'TURKEY' },
    { value: 'TZ', name: 'TANZANIA' },
    { value: 'UC', name: 'TURT MTN CHIPPEWA' },
    { value: 'UG', name: 'UGANDA' },
    { value: 'UK', name: 'UKRAINE' },
    { value: 'UM', name: 'MAURITIUS' },
    { value: 'UR', name: 'TURKMENISTAN' },
    { value: 'US', name: 'UNITED STATES' },
    { value: 'UV', name: 'BURKINA FASO' },
    { value: 'UY', name: 'URUGUAY' },
    { value: 'UZ', name: 'UZBEKISTAN' },
    { value: 'VB', name: 'BRITISH VIRGIN ISLANDS' },
    { value: 'VC', name: 'VERACRUZ' },
    { value: 'VI', name: 'VIRGIN ISLANDS (UNITED STATES)' },
    { value: 'VL', name: 'NAVASSA ISLAND' },
    { value: 'VV', name: 'ST. VINCENT/GRENADIN' },
    { value: 'VY', name: 'VATICAN CITY' },
    { value: 'VZ', name: 'VENEZUELA' },
    { value: 'WB', name: 'WEST BANK' },
    { value: 'WE', name: 'WHITE EARTH' },
    { value: 'WF', name: 'WALLIS/FUTUNA' },
    { value: 'WK', name: 'WAKE ISLAND' },
    { value: 'WL', name: 'WALES' },
    { value: 'WN', name: 'WEST INDIES' },
    { value: 'WS', name: 'WESTERN SAMOA' },
    { value: 'XX', name: 'UNKNOWN' },
    { value: 'YG', name: 'YUGOSLAVIA' },
    { value: 'YO', name: 'MAYOTTE' },
    { value: 'YT', name: 'YUKON TERRITORY' },
    { value: 'YU', name: 'YUCATAN' },
    { value: 'YY', name: 'ALL OTHERS' },
    { value: 'ZA', name: 'ZACATECAS' },
    { value: 'ZB', name: 'MARTINIQUE' },
    { value: 'ZC', name: 'SURINAM' },
    { value: 'ZI', name: 'CANARY ISLANDS' },
    { value: 'ZM', name: 'ZAMBIA' },
    { value: 'ZO', name: 'MOZAMBIQUE' },
    { value: 'ZR', name: 'ZAIRE' }
  ];

  paymentOptions: RefData[] = [
    { name: 'Credit Card', value: 'APP_CC'  },
    { name: 'Money Order', value: 'APP_MO' },
    { name: 'Agency', value: 'AGENCY' }
  ];

  raceOptions: RefData[] = [
    { name: 'Asian or Pacific Islander', value: 'A' },
    { name: 'Black', value: 'B' },
    { name: 'American Indian and Alaskan Native', value: 'I' },
    { name: 'Unknown', value: 'U' },
    { name: 'White (includes Mexicans and Latinos)', value: 'W' }
  ];

  genderOptions: RefData[] = [
    { name: 'Female', value: 'F' },
    { name: 'Male', value: 'M' },
    { name: 'Unknown', value: 'U' }
  ];

  suffixOptions: RefData[] = [
    { value: 'JR', name: 'JR' },
    { value: 'SR', name: 'SR' },
    { value: 'II', name: 'II' },
    { value: 'III', name: 'III' },
    { value: 'IV', name: 'IV' }
  ];

  agencyNameOptions: string[] = [
    'Department of Health',
    'Investigation Services',
    'Schools System',
    'Government',
    'Bureau of Investigations',
    'State Police'
  ];

  applicantFirstNameOptions: string[] = [
    'John', 'Amy', 'Bob', 'Gene', 'Sam', 'Justin', 'Olivia', 'Larry', 'Elle', 'Vivian', 'Shawn', 'Seven'
  ];

  applicantLastNameOptions: string[] = [
    'Davids', 'Reynolds', 'Johnston', 'Green', 'Parker', 'James', 'Revis', 'Harbaugh', 'Ealy', 'Thomas'
  ];


  reasonOptions: string[] = [
    'Passport Application', 'Background Investigation', 'Permit Re-Certification', 'Other'
  ]

  agencyServiceLevels: AgencyServiceLevel[] = [
    {
      id: '0000000AA',
      name: 'TEST_LEVEL_ONE',
      stateCode: 'GA',
      serviceLevel: "State Check Only",
      electronicFee: 36.25,
      paperFee: 44.25,
      agencyElectronicFeePercent:50,
      agencyPaperFeePercent:50
    },
    {
      id: '0000000AA',
      name: 'TEST_LEVEL_TWO',
      stateCode: 'GA',
      serviceLevel: "State and National Check",
      electronicFee: 54.95,
      paperFee: 89.95,
      agencyElectronicFeePercent:67.5,
      agencyPaperFeePercent:67.5
    },
    {
      id: '0000000AA',
      name: 'TEST_LEVEL_THREE',
      stateCode: 'GA',
      serviceLevel: "State and Local Check",
      electronicFee: 49.95,
      paperFee: 69.95,
      agencyElectronicFeePercent:100,
      agencyPaperFeePercent:100
    },
  ];

  agency: Agency = {
    active: true,
    activeChangeDate: '1538152435054',
    id: "5b7c616a447cb946b063e6bc",
    stateCode: "GA",
    name: "The First Agency",
    ori: "GA testing Agency 1",
    privacyId: "5bad3f67d601800001a35846",
    email: "agency@napstest.com",
    address: {
      address1: "12345 Any Street",
      address2: null,
      city: "Arlington",
      state: "GA",
      suite: null,
      zip: "02587",
    },
    reasons:[
      {
        agencyServiceLevelId: "5b7c5f73447cb946b063e6b2",
        agencyServiceLevelName: "asl1",
        description: "reason 1 description",
        name: "reason1"
      },
      {
        agencyServiceLevelId: "5b7c5f8a447cb946b063e6b4",
        agencyServiceLevelName: "asl2",
        description: "reason 2 description",
        name: "reason2"
      },
      {
        agencyServiceLevelId: "5ba534774cedfd00015bf3c0",
        agencyServiceLevelName: "New Service Level",
        description: "description3",
        name: "reason3"
      }
    ]
  };

  applicant: Applicant = {
    id: null,
    stateCode: null,
    status: null,
    confirmation: null,
    qrCode: null,
    transaction: {
      reviewingAgency: this.agency.name,
      reviewingAgencyId: this.agency.id,
      reviewingAgencyServiceLevel: this.agencyServiceLevels[0],
      requestingAgencyId: null,
      reason: this.agency.reasons[0],
      appliedPosition: this.agency.reasons[0].name
    },
    person: {
      lastName: "Doe",
      firstName: "John",
      middleName: null,
      suffix: null,
      ssn: null,
      dateOfBirth: "10011978",
      placeOfBirth: "GA",
      countryOfCitizenship: "US",
      gender: "M",
      race: "U",
      height: "602",
      weight: "185",
      eyeColor: "BLK",
      hairColor: "BRO",
      phone: "2603359855",
      email: null,
      driversLicenseNumber: null,
      stateDriversLicense: null
    },
    address: {
      address1: "12345 Any Street",
      address2: null,
      suite: null,
      city: "Gainsville",
      state: "GA",
      zip: "12345"
    },
    payment: {
      amount: null,
      eCheck: null,
      hashCC: null,
      paymentMethod: null,
      paymentType: null,
      verifyTransaction: null,
      creditCard: null,
      billingAddress: null
    }
  };

  paymentMethodOptions: any[] = [
    {
      name: "ON_SITE",
      message: "On Site",
      paymentTypes:[]
    },
    {
      name: "MAIL_IN",
      message: "Mail In",
      paymentTypes:[]
    },
    {
      name: "ELECTRONIC",
      message: "Electronic",
      paymentTypes:  [
        {
          name: "ECHECK",
          message: "eCheck"
        },
        {
          name: "CREDIT_CARD",
           message: "Credit Card"
         }
       ]
     }
   ];

  constructor(){
    this.generateApplicant();
    // console.log(JSON.stringify(this.citizenshipOptions))
    // console.log(JSON.stringify(this.eyeColorOptions))
    // console.log(JSON.stringify(this.hairColorOptions))
    // console.log(JSON.stringify(this.heightOptions))
    // console.log(JSON.stringify(this.placeOfBirthOptions))
    // console.log(JSON.stringify(this.paymentOptions))
    // console.log(JSON.stringify(this.raceOptions))
    // console.log(JSON.stringify(this.genderOptions))
    // console.log(JSON.stringify(this.suffixOptions))
  }

  generateApplicant(confirm?: boolean) {
    let firstNameIndex = Math.floor(Math.random() * (this.applicantFirstNameOptions.length - 2 + 1)) + 1;
    let middleNameIndex = Math.floor(Math.random() * (1 - 0 + 1)) + 0;
    let fingerPrintCardUserIndex = Math.floor(Math.random() * (1 - 0 + 1)) + 0;
    let lastNameIndex = Math.floor(Math.random() * (this.applicantLastNameOptions.length - 2 + 1)) + 1;
    let agencyNameIndex = Math.floor(Math.random() * (this.agencyNameOptions.length - 2 + 1)) + 1;
    let reasonIndex = Math.floor(Math.random() * (this.agency.reasons.length - 2 + 1)) + 1;
    let methodsIndex = Math.floor(Math.random() * (this.paymentMethodOptions.length - 2 + 1)) + 1;
    this.applicant.person.firstName = this.applicantFirstNameOptions[firstNameIndex];
    if(middleNameIndex > 0) this.applicant.person.middleName = this.applicantFirstNameOptions[lastNameIndex];
    this.applicant.person.lastName = this.applicantLastNameOptions[lastNameIndex];
    this.applicant.stateCode = "GA";
    this.applicant.person.email = this.generateEmailAddress(this.applicant.person.firstName, this.applicant.person.lastName);
    this.applicant.transaction.reviewingAgencyId = this.agency.id;
    this.applicant.transaction.reviewingAgency = this.agency.name;
    this.applicant.transaction.reason = this.agency.reasons[reasonIndex];
    this.applicant.payment.paymentMethod = this.paymentMethodOptions[2].name;
    if(this.paymentMethodOptions[methodsIndex].name === 'ELECTRONIC') {
      let mm = (Math.floor(Math.random() * (12 - 1)) + 1).toString();
      let yy = (Math.floor(Math.random() * ((parseInt(new Date().getFullYear().toString().slice(-2)) + 4) - (parseInt(new Date().getFullYear().toString().slice(-2)) + 1))) + (parseInt(new Date().getFullYear().toString().slice(-2)) + 1)).toString();
      if(mm.length < 2) mm = '0'+mm;
      if(yy.length < 2) yy = '0'+yy;
      let exDate = mm+yy;
      this.applicant.payment.paymentType = 'CREDIT_CARD';
      this.applicant.payment.creditCard = {
        cardType: "Visa",
        cardHolder: this.applicant.person.firstName+' '+this.applicant.person.lastName,
        cardNumber: "5148875063870734",
        cvv: (Math.floor(Math.random() * (999 - 100)) + 100).toString(),
        expirationDate: exDate
      };
      this.applicant.payment.billingAddress =  {
        address1: "12345 Any Street",
        address2: null,
        city: "Gainsville",
        suite: null,
        state: "GA",
        zip: (Math.floor(Math.random() * (99999 - 10001)) + 10001).toString()
      }
    }
    if(confirm) {
      this.applicant.id = "5b3e5fa146e0fb00018f72c2";
      this.applicant.status = "REGISTERED";
      this.applicant.confirmation = "UCBHFQW6D7J5";
      this.applicant.qrCode = "iVBORw0KGgoAAAANSUhEUgAAAH0AAAB9AQAAAACn+1GIAAAA80lEQVR42u3VMQ7DIAwFUEsM2coFKnENb5ypF0jgAnAltlwDiQswMkS4ztI2E2ZrpVoZojcQ88EK0LUa/OFrwYGKZAKAFkOkEpPqll+kEKD4VjqqKXCYb5NQ0YQZ4E6dpWvrA+A8ApZrQAPg6kvWl2MYgG+qY9721xpjoGaITGyKxNCxVAtcmxgoHY9GPuUZgG03dTnk4PAAPqVmohg6cOR5xffmhkD7HRZeKWsxeFIVi4MJOJu1Z+pRDHyDiOCGn2M6gHPmGj+v1MdwzlwyDgrNAF+6Fe56BioYt3x+dgDcqU8ULMiB83A2rzZrMfx/BT8ATwW0YFzRNL3GAAAAAElFTkSuQmCC";
      this.applicant.transaction.reason = this.agency.reasons[reasonIndex];
    }
  }

  generateEmailAddress(firstName: string, lastName: string): string {
    let num = Math.floor(Math.random() * (500 - 1 + 1)) + 1;
    return lastName+'.'+firstName+num.toString()+'@test.com';
  }

}
